[package]
name = "csharp-tree-sitter-utils-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.17.1"
tree-sitter-c-sharp = "0.16"

[dev-dependencies]
colored = "2.1.0"
regex = "1.10.4"
